import Link from 'next/link'
import { redirect } from 'next/navigation'
import { layPhien } from '@/lib/xac-thuc/phien'
import { db } from '@/lib/db/pool'
import { dangXuat } from '@/app/dang-nhap/actions'
import { TaoTaiKhoan, ThaoTacTaiKhoan, TaoNguoiLayHd, SuaNguoiLayHd, ThaoTacNguoiLayHd, TaoDonVi, SuaDonVi, ThaoTacDonVi, TaoCanBo, SuaCanBo, ThaoTacCanBo, type CanBoAdmin } from './forms'

const vaiTro = { admin: 'Quản trị viên', nhap_lieu: 'Nhập liệu', chi_doc: 'Chỉ đọc' }
export default async function AdminPage() {
  const phien = await layPhien()
  if (!phien) redirect('/dang-nhap')
  if (phien.vai_tro !== 'admin') redirect('/dashboard')
  const [{ rows: users }, { rows: people }, { rows: donVi }, { rows: canBo }] = await Promise.all([
    db.query<{ id: string; ten_dang_nhap: string; ho_ten: string; vai_tro: keyof typeof vaiTro; dang_hoat_dong: boolean }>('select id,ten_dang_nhap,ho_ten,vai_tro,dang_hoat_dong from nguoi_dung order by dang_hoat_dong desc,tao_luc desc,id'),
    db.query<{ id: string; ten: string; ty_le_phi: string | null; ngan_hang_bin: string | null; so_tai_khoan: string | null; ten_ngan_hang: string | null; ten_chu_tk: string | null; can_bo_id: string | null; chi_nhanh: string | null; ghi_chu: string | null; dang_hoat_dong: boolean }>('select id,ten,ty_le_phi,ngan_hang_bin,so_tai_khoan,ten_ngan_hang,ten_chu_tk,can_bo_id,chi_nhanh,ghi_chu,dang_hoat_dong from nguoi_lay_hd order by dang_hoat_dong desc,ten'),
    db.query<{ id: string; ten: string; ghi_chu: string | null; dang_hoat_dong: boolean }>('select id,ten,ghi_chu,dang_hoat_dong from don_vi order by dang_hoat_dong desc,ten'),
    // Cán bộ là người ký trên giấy đề nghị; tài khoản đăng nhập gắn với cán bộ để suy ra phòng.
    db.query<CanBoAdmin>('select id,ho_ten,gioi_tinh,chuc_danh,phong,la_lanh_dao,dang_hoat_dong,nguoi_dung_id from can_bo order by dang_hoat_dong desc,ho_ten'),
  ])
  const chonCanBo = canBo.map(cb => ({ id: cb.id, ten: cb.ho_ten }))
  const chonNguoiDung = users.map(nd => ({ id: nd.id, ten: `${nd.ho_ten} (${nd.ten_dang_nhap})` }))
  const tenCanBo = new Map(canBo.map(cb => [cb.id, cb.ho_ten]))
  const tenNguoiDung = new Map(users.map(nd => [nd.id, nd.ho_ten]))
  return <main className="min-h-screen px-4 py-8 sm:px-8 [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:tracking-tight [&_h2]:text-lg [&_h2]:font-semibold [&_small]:text-xs [&_small]:font-normal [&_small]:text-slate-500 [&_summary]:cursor-pointer [&_summary]:font-medium [&_summary]:text-indigo-700">
    <header className="mx-auto mb-8 flex max-w-7xl flex-wrap items-center justify-between gap-6 [&_nav]:flex [&_nav]:flex-wrap [&_nav]:items-center [&_nav]:gap-5 [&_p]:mt-2 [&_p]:text-slate-600"><div><p className="mb-2 text-xs font-bold tracking-widest text-indigo-700">QUẢN TRỊ HỆ THỐNG</p><h1>Quản lý tài khoản</h1><p>Cấp quyền truy cập phù hợp, bảo toàn dữ liệu và lịch sử thao tác.</p></div><nav><Link href="/dashboard">Tổng quan</Link><Link href="/giao-dich">Sổ giao dịch</Link><Link href="/tep">Hồ sơ tệp</Link><Link href="/cai-dat">Cài đặt</Link><form action={dangXuat}><button className="btn btn-secondary">Đăng xuất</button></form></nav></header>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Tạo tài khoản mới</h2><p>Thông tin đăng nhập được cấp trực tiếp bởi quản trị viên.</p></div></div><TaoTaiKhoan /></section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Danh sách tài khoản</h2><p>Vô hiệu hóa thay cho xóa vĩnh viễn để giữ nguyên lịch sử tài chính.</p></div><span className="badge neutral">{users.length} tài khoản</span></div>
      <div className="overflow-x-auto [&_table]:w-full [&_table]:text-left [&_table]:text-sm [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-slate-200 [&_th]:bg-slate-50 [&_th]:px-4 [&_th]:py-3 [&_th]:text-xs [&_th]:font-semibold [&_th]:text-slate-600 [&_td]:min-w-36 [&_td]:border-b [&_td]:border-slate-100 [&_td]:p-4 [&_td]:align-top [&_tr:last-child_td]:border-0"><table><thead><tr><th>Người dùng</th><th>Vai trò</th><th>Trạng thái</th><th>Quản lý truy cập</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.ho_ten}</strong><span className="mt-1 block break-all text-xs text-slate-500">{user.ten_dang_nhap}</span>{user.id === phien.id && <span className="mt-2 block text-xs font-medium text-indigo-700">Tài khoản của bạn</span>}</td><td>{vaiTro[user.vai_tro]}</td><td><span className={`badge neutral ${user.dang_hoat_dong ? 'good' : ''}`}>{user.dang_hoat_dong ? 'Đang hoạt động' : 'Đã vô hiệu hóa'}</span></td><td><ThaoTacTaiKhoan id={user.id} ten={user.ten_dang_nhap} active={user.dang_hoat_dong} self={user.id === phien.id} /></td></tr>)}</tbody></table></div>
    </section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Thêm cán bộ</h2><p>Giới tính, chức danh và phòng là những chữ in thẳng lên giấy đề nghị.</p></div></div><TaoCanBo nguoiDung={chonNguoiDung} /></section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Danh sách cán bộ</h2><p>Vô hiệu hóa thay cho xóa để giấy đã in vẫn tra được người ký.</p></div><span className="badge neutral">{canBo.length} cán bộ</span></div>
      {canBo.length ? <div className="overflow-x-auto [&_table]:w-full [&_table]:text-left [&_table]:text-sm [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-slate-200 [&_th]:bg-slate-50 [&_th]:px-4 [&_th]:py-3 [&_th]:text-xs [&_th]:font-semibold [&_th]:text-slate-600 [&_td]:min-w-36 [&_td]:border-b [&_td]:border-slate-100 [&_td]:p-4 [&_td]:align-top [&_tr:last-child_td]:border-0"><table><thead><tr><th>Cán bộ</th><th>Phòng</th><th>Tài khoản đăng nhập</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{canBo.map(cb => <tr key={cb.id}><td><strong>{[cb.gioi_tinh, cb.ho_ten].filter(Boolean).join(' ')}</strong>{cb.chuc_danh && <span className="mt-1 block text-sm text-slate-500">{cb.chuc_danh}</span>}{cb.la_lanh_dao && <span className="mt-2 block text-xs font-medium text-indigo-700">Lãnh đạo — người ký duyệt</span>}</td><td>{cb.phong || <span className="text-slate-500">{cb.la_lanh_dao ? 'Không thuộc phòng nào' : '—'}</span>}</td><td>{cb.nguoi_dung_id ? tenNguoiDung.get(cb.nguoi_dung_id) ?? <span className="text-slate-500">Không tìm thấy</span> : <span className="text-slate-500">Chưa gắn</span>}</td><td><span className={`badge neutral ${cb.dang_hoat_dong ? 'good' : ''}`}>{cb.dang_hoat_dong ? 'Đang hoạt động' : 'Đã vô hiệu hóa'}</span></td><td><details><summary>Quản lý</summary><SuaCanBo canBo={cb} nguoiDung={chonNguoiDung} /><ThaoTacCanBo id={cb.id} ten={cb.ho_ten} active={cb.dang_hoat_dong} /></details></td></tr>)}</tbody></table></div> : <p className="py-6 text-sm text-slate-500">Chưa có cán bộ nào.</p>}
    </section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Thêm người lấy hóa đơn</h2><p>Cấu hình thông tin và tỷ lệ phí cho người đại diện lấy hóa đơn.</p></div></div><TaoNguoiLayHd canBo={chonCanBo} /></section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Danh sách người lấy hóa đơn</h2><p>Quản lý thông tin người đại diện lấy hóa đơn và tỷ lệ phí.</p></div><span className="badge neutral">{people.length} người</span></div>
      {people.length ? <div className="overflow-x-auto [&_table]:w-full [&_table]:text-left [&_table]:text-sm [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-slate-200 [&_th]:bg-slate-50 [&_th]:px-4 [&_th]:py-3 [&_th]:text-xs [&_th]:font-semibold [&_th]:text-slate-600 [&_td]:min-w-36 [&_td]:border-b [&_td]:border-slate-100 [&_td]:p-4 [&_td]:align-top [&_tr:last-child_td]:border-0"><table><thead><tr><th>Người lấy HĐ</th><th>Tỷ lệ phí</th><th>Tài khoản nhận tiền</th><th>Cán bộ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{people.map(person => <tr key={person.id}><td><strong>{person.ten}</strong>{person.ghi_chu && <span className="mt-1 block text-sm text-slate-500">{person.ghi_chu}</span>}</td><td>{person.ty_le_phi === null ? 'Theo tỷ lệ chung' : `${(Number(person.ty_le_phi) * 100).toFixed(2)}%`}</td><td>{person.so_tai_khoan ? <span>{person.ten_chu_tk || 'N/A'}<span className="mt-1 block break-all text-xs text-slate-500">{person.so_tai_khoan}{person.ten_ngan_hang ? ` – ${person.ten_ngan_hang}` : person.ngan_hang_bin ? ` (BIN: ${person.ngan_hang_bin})` : ''}{person.chi_nhanh ? ` – Chi nhánh: ${person.chi_nhanh}` : ''}</span></span> : <span className="text-slate-500">Chưa cấu hình</span>}</td><td>{person.can_bo_id ? tenCanBo.get(person.can_bo_id) ?? <span className="text-slate-500">Không tìm thấy</span> : <span className="text-slate-500">—</span>}</td><td><span className={`badge neutral ${person.dang_hoat_dong ? 'good' : ''}`}>{person.dang_hoat_dong ? 'Đang hoạt động' : 'Đã vô hiệu hóa'}</span></td><td><details><summary>Quản lý</summary><SuaNguoiLayHd nguoi={person} canBo={chonCanBo} /><ThaoTacNguoiLayHd id={person.id} ten={person.ten} active={person.dang_hoat_dong} /></details></td></tr>)}</tbody></table></div> : <p className="py-6 text-sm text-slate-500">Chưa có người lấy hóa đơn.</p>}
    </section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Thêm đơn vị</h2><p>Thêm các đơn vị để quản lý lịch sử tiếp khách.</p></div></div><TaoDonVi /></section>
    <section className="card mx-auto mb-6 max-w-7xl p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4 [&_p]:mt-2 [&_p]:text-sm [&_p]:text-slate-500"><div><h2>Danh sách đơn vị</h2><p>Quản lý các đơn vị được tiếp. Ưu tiên hiển thị đơn vị chưa tiếp trong năm hoặc tiếp xa nhất.</p></div><span className="badge neutral">{donVi.length} đơn vị</span></div>
      {donVi.length ? <div className="overflow-x-auto [&_table]:w-full [&_table]:text-left [&_table]:text-sm [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-slate-200 [&_th]:bg-slate-50 [&_th]:px-4 [&_th]:py-3 [&_th]:text-xs [&_th]:font-semibold [&_th]:text-slate-600 [&_td]:min-w-36 [&_td]:border-b [&_td]:border-slate-100 [&_td]:p-4 [&_td]:align-top [&_tr:last-child_td]:border-0"><table><thead><tr><th>Tên đơn vị</th><th>Ghi chú</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{donVi.map(dv => <tr key={dv.id}><td><strong>{dv.ten}</strong></td><td>{dv.ghi_chu || <span className="text-slate-500">—</span>}</td><td><span className={`badge neutral ${dv.dang_hoat_dong ? 'good' : ''}`}>{dv.dang_hoat_dong ? 'Đang hoạt động' : 'Đã vô hiệu hóa'}</span></td><td><details><summary>Quản lý</summary><SuaDonVi donVi={dv} /><ThaoTacDonVi id={dv.id} ten={dv.ten} active={dv.dang_hoat_dong} /></details></td></tr>)}</tbody></table></div> : <p className="py-6 text-sm text-slate-500">Chưa có đơn vị nào.</p>}
    </section>
  </main>
}
